import Link from "next/link"
import "../globals.css"
import { Inter } from "next/font/google"
import { getPages } from "@/sanity/sanity-utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "My Personal Website",
  description: "Generated by NextJS 13 + Sanity",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body className={`${inter.className}`} >
        <header className="max-w-5xl mx-auto bg-white px-4 py-5 top-0 sticky flex items-center justify-between">
          <Link className="bg-gradient-to-l from-orange-400 via-red-500 to-purple-700 bg-clip-text text-transparent text-2xl drop-shadow font-extrabold p-4" href={'/'}> @heblopez </Link>
          <div className="flex items-center gap-12 text-md font-semibold text-purple-700">
            {pages.map((page) => (<Link key={page._id} href={`/${page.slug}`} className="hover:underline hover:text-purple-600 transition">{page.title}</Link>))}
          </div>        
        </header>
        <main className="max-w-5xl mx-auto px-8 py-16">{children}</main>
      </body>
    </html>
  )
}
